/**
 * Shared TypeScript types across the application.
 * DB-level types are generated by Prisma — these are view/API-level types.
 */

import type { PostStatus, PostType } from "@prisma/client";

// Re-export Prisma enums for convenience
export type { PostStatus, PostType };

// ---------------------------------------------------------------------------
// API payloads
// ---------------------------------------------------------------------------

export interface CreatePostPayload {
  title: string;
  content?: string;
  excerpt?: string;
  type: PostType;
  categoryId?: string;
  tagIds?: string[];
  // slug is NOT accepted — generated server-side on creation
}

export interface UpdatePostPayload {
  title?: string;
  content?: string;
  excerpt?: string;
  status?: PostStatus;
  categoryId?: string | null;
  tagIds?: string[];
  // slug is intentionally absent — the API ignores it even if sent
}

export interface CreateCategoryPayload {
  name: string;
  slug?: string; // auto-generated from name if omitted
  description?: string;
  order?: number;
}

export interface CreateTagPayload {
  name: string;
  slug?: string;
}

// ---------------------------------------------------------------------------
// Autosave editor state
// ---------------------------------------------------------------------------

export type SaveStatus = "unsaved" | "saving" | "saved" | "error";

// ---------------------------------------------------------------------------
// Lightweight view types (what pages receive as props)
// ---------------------------------------------------------------------------

export interface PostSummary {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  status: PostStatus;
  type: PostType;
  publishedAt: Date | null;
  createdAt: Date;
  category: { name: string; slug: string } | null;
  tags: { name: string; slug: string }[];
}

export interface CategoryWithCount {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  order: number;
  _count: { posts: number };
}
